### PR TITLE
unbreak swaggo doc generation for Identity object

### PR DESCRIPTION
**Pull request by dinghram**
The implementation that enabled IP addresses in certificate alternative names added an example that broke swaggo doc generation. This PR removes the example, which should allow swaggo to generate docs for the Identity object.

### CODE REVIEW

**Review by ZenkieBear — APPROVED** [review]
👍

**Review by kairoaraujo — APPROVED** [review]

**Comment by necheffa** [comment]
It looks like since a new field was added to `goca.Identity` the reference output for swagger documentation also needs updated to prevent make from kicking back a non-success return to the shell (probably will make the pipeline unhappy).

Reference docs are `doc/swagger.json` and `doc/swagger.yaml`. I would think checking in a copy of the new generated docs would be sufficient to button this up.

**Comment by dinghram** [comment]
> It looks like since a new field was added to `goca.Identity` the reference output for swagger documentation also needs updated to prevent make from kicking back a non-success return to the shell (probably will make the pipeline unhappy).
> 
> Reference docs are `doc/swagger.json` and `doc/swagger.yaml`. I would think checking in a copy of the new generated docs would be sufficient to button this up.

I've checked in a fix, I hope it is what you are looking for.

**Review by ZenkieBear — COMMENTED** [review]
LGTM

**Review by necheffa — APPROVED** [review]
LGTM

**Pull request merged**
